function [cal, fit] = rad_read_nutnr_calfile(calfilename, wvl_range)
%.. desiderio 16-nov-2020  commented out warning, no T_CAL_SWA found.
%..                        added datenumber field.
%.. desiderio 13-nov-2020  renamed the 'factory_' fields to 'ISS_' fields.
%.. desiderio 10-nov-2020  adapted for code to tabulate processing offsets
%..                        (a) added filename field
%..                        (b) added factory_caldate field
%..                        (c) added factory_calname field
%.. desiderio 29-sep-2017  added T_Cal_Swa to parsed values
%.. desiderio 16-sep-2015
%
%.. reads in calcoeffs from the input Satlantic comma-delimited ISUS or
%.. SUNA cal file.
%
%.. wvl_range is a 2 element vector which contains the lower and upper
%.. wavelength limits used in the Satlantic fitting routines to calculate
%.. nitrate concentration. Default setting is [217.0 240.0].
%
%.. output structure cal contains values for all 256 wavelength channels.
%
%.. output structure fit contains values for only the wavelength 
%.. channels used in the fitting routines.
%
%.. calfilename must include the full path of the calfile unless
%.. the file is located in the working directory.

if nargin==1
    wvl_range = [217 240];
end

fid = fopen(calfilename);
if fid < 0
    error(['Could not find input file ' calfilename]);
end
%.. read in all lines.
C = textscan(fid, '%s', 'whitespace', '', 'delimiter', '\n');
fclose(fid);
%.. get rid of wrapping cell array
C = C{1};

%.. write out filename to structure
[~, name, ~] = fileparts(calfilename);
cal.filename = name;  % don't bother with extension

%.. determine whether the instrument is an isus or suna.
%.. this info is on the first line.
cal.instrument = C{1}(3:6);

%.. parse into cal data structure
cal.sernum = sscanf(C{1}(8:11), '%u');  % instrument serial number
%.. find caldate.
%.. calfiles generated by Satlantic at the factory and by users using
%.. ISUSCom both have the relevant caldate and time on the 4th row
%.. of the calfile. So, directly read it out.
cal.date = C{4}(22:32);  % dd-mmm-yyyy
%.. also add serial datenumber including time
cal.datenumber = datenum(C{4}(22:41));  % dd-mmm-yyyy hh:mm:ss
%.. find factory cal temperature
%.. NOTE: the factory value in any ISUS or SUNA cal file should NEVER be
%..       changed by the user; the fitting extinction coeffs in the cal
%..       file are tied to whatever the factory value is, and not to
%..       the temperature of the water used in a non-factory cal.
%
%.. 2017-09-29
%.. new cal files have 2 entries for a calibration temperature:
%.. T_CAL
%.. T_CAL_SWA

tf_tcal = strncmpi('H,T_CAL ',C,8);
if sum(tf_tcal)==0
    disp(['No T_CAL line in ' calfilename]);
    cal.tcal = [];
elseif sum(tf_tcal)>1
    error(['Too many T_CAL lines in ' calfilename]);
else
    %.. try to make this read as general as possible without failing
    %.. on some idiosyncratic CAL file formats.
    str = strrep(C{tf_tcal},',',' ');
    str = [str '        '];
    cal.tcal = sscanf(str(9:15), '%f');
    %.. round to the millidegree
    cal.tcal = round(1000*cal.tcal) * 0.001;
end

tf_tcal_swa = strncmpi('H,T_CAL_SWA',C,11);
if sum(tf_tcal_swa)==0
    %disp(['No T_CAL_SWA line in ' calfilename]);
    cal.tcal_swa = [];
elseif sum(tf_tcal_swa)>1
    error(['Too many T_CAL_SWA lines in ' calfilename]);
else
    %.. try to make this read as general as possible without failing
    %.. on some idiosyncratic CAL file formats.
    str = strrep(C{tf_tcal_swa},',',' ');
    str = [str '        '];
    cal.tcal_swa = sscanf(str(13:19), '%f');
    %.. round to the millidegree
    cal.tcal_swa = round(1000*cal.tcal_swa) * 0.001;
end

%.. find header row just before the caldata to be read in
tf_row0 = strcmpi('H,Wavelength,NO3,SWA,TSWA,Reference',C);
if sum(tf_row0)~=1
    error(' Check CAL file header row with array variable names.');
end
%.. set up array data for vectorized sscanf read.
C = strrep(C, 'E', ' ');
C = strrep(C, ',', ' ');
idx = (1:256) + find(tf_row0);
data = sscanf(char(C(idx))', '%f');
data = reshape(data, 5, 256)';
cal.wvl  = data(:,1);   % wavelengths
cal.eno3 = data(:,2);   % ext coeffs for nitrate
cal.eswa = data(:,3);   % ext coeffs for seawater
cal.tswa = data(:,4);   % ext coeffs for seawater, temperature dependent
cal.ref  = data(:,5);   % cal purewater reference spectrum

%.. the most recent factory calibration name (letter) is not 
%.. always encoded in the first row. Initialize as empty set. 
%.. The programs to figure re-processing offsets will deal
%.. with this.
cal.ISS_calname = '';

%.. write factory caldate, which will be contained in the last 
%.. File creation time row. This cal will have been created by
%.. the "Internal Software Suite" and not SUNA.com. Even if the
%.. factory does a SUNA cal after the ISS cal I want the ISS caldate
%.. because that is the one which writes in all the column coeffs 
%.. (SUNAcom cals just replace the DI Reference column values).
fileCreationTimeRows = C(contains(C, 'File creation time')); 
cal.ISS_caldate  = fileCreationTimeRows{end}(22:32);

clear C

%.. also export only the values in the range [217.0 240.0]
wvl_mask     =     wvl_range(1) <= cal.wvl   &   cal.wvl <= wvl_range(2);
data = data(wvl_mask, :);  % keep only the fitting wavelength channels
%.. rinse and repeat
fit.instrument = cal.instrument;
fit.sernum = cal.sernum;
fit.date = cal.date;
fit.tcal = cal.tcal;
fit.tcal_swa = cal.tcal_swa;
fit.wvl  = data(:,1);   % wavelengths
fit.eno3 = data(:,2);   % ext coeffs for nitrate
fit.eswa = data(:,3);   % ext coeffs for seawater
fit.tswa = data(:,4);   % ext coeffs for seawater, temperature dependent
fit.ref  = data(:,5);   % cal purewater reference spectrum
